### ISSUE TITLE
IO Exception on execution

### ISSUE THREAD

**Issue by alexquast** [mwaylabs/relution-jenkins-plugin#1]
The plugin refuses to upload a binary to relution. During build run the following error occurs

```
[ArtifactPublisher] Publishing 'platforms/android/ant-build/MainActivity-debug.apk' to 'live.relution.io - xxxxxxx@ox'
ERROR: Publisher org.jenkinsci.plugins.relution_publisher.configuration.jobs.ArtifactPublisher aborted due to exception
java.io.IOException: remote file operation failed: /Users/jenkins/jenkins/workspace/buildMailAppAndroid/Buildnode/MobileWebAppMac at hudson.remoting.Channel@24f04e9d:MobileWebAppMac: java.io.IOException: Unable to serialize hudson.FilePath$FileCallableWrapper@39eedcce
    at hudson.FilePath.act(FilePath.java:985)
    at hudson.FilePath.act(FilePath.java:967)
    at org.jenkinsci.plugins.relution_publisher.configuration.jobs.ArtifactPublisher.publish(ArtifactPublisher.java:127)
    at org.jenkinsci.plugins.relution_publisher.configuration.jobs.ArtifactPublisher.perform(ArtifactPublisher.java:92)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
    at hudson.model.Build$BuildExecution.post2(Build.java:183)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
    at hudson.model.Run.execute(Run.java:1775)
    at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
Caused by: java.io.IOException: Unable to serialize hudson.FilePath$FileCallableWrapper@39eedcce
    at hudson.remoting.UserRequest.serialize(UserRequest.java:169)
    at hudson.remoting.UserRequest.<init>(UserRequest.java:63)
    at hudson.remoting.Channel.call(Channel.java:750)
    at hudson.FilePath.act(FilePath.java:978)
    ... 12 more
Caused by: java.io.NotSerializableException: hudson.matrix.MatrixRun
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1183)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1508)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1547)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1508)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1431)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1177)
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347)
    at hudson.remoting.UserRequest._serialize(UserRequest.java:158)
    at hudson.remoting.UserRequest.serialize(UserRequest.java:167)
    ... 15 more
```

It's Master/Slave Jenkins setup. The Master spawns the build job on a Mac Mini running latest Java 8 and OS X Yosemite. The Relution plugin is configured correctly, connection tests are successful in configuration.

**Comment by mboesch** [comment]
I can confirm this issue:

<pre><code>[ArtifactPublisher] Publishing 'iOS/bin/iPhone/Ad-Hoc/*ipa' to 'xxx.yyy.com - zzz@abc'
ERROR: Publisher org.jenkinsci.plugins.relution_publisher.configuration.jobs.ArtifactPublisher aborted due to exception
java.io.IOException: remote file operation failed: /Users/michaelbosch/Jenkins/workspace/InCab_App_iOS at hudson.remoting.Channel@72be5b10:MacMini: java.io.IOException: Unable to serialize hudson.FilePath$FileCallableWrapper@18fb05a9
    at hudson.FilePath.act(FilePath.java:985)
    at hudson.FilePath.act(FilePath.java:967)
    at org.jenkinsci.plugins.relution_publisher.configuration.jobs.ArtifactPublisher.publish(ArtifactPublisher.java:127)
    at org.jenkinsci.plugins.relution_publisher.configuration.jobs.ArtifactPublisher.perform(ArtifactPublisher.java:92)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
    at hudson.model.Build$BuildExecution.post2(Build.java:183)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
    at hudson.model.Run.execute(Run.java:1776)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
Caused by: java.io.IOException: Unable to serialize hudson.FilePath$FileCallableWrapper@18fb05a9
    at hudson.remoting.UserRequest.serialize(UserRequest.java:169)
    at hudson.remoting.UserRequest.<init>(UserRequest.java:63)
    at hudson.remoting.Channel.call(Channel.java:751)
    at hudson.FilePath.act(FilePath.java:978)
    ... 12 more
Caused by: java.io.NotSerializableException: hudson.model.FreeStyleBuild
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
    at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
    at hudson.remoting.UserRequest._serialize(UserRequest.java:158)
    at hudson.remoting.UserRequest.serialize(UserRequest.java:167)
    ... 15 more</code></pre>

We're also using a Master/Slave Jenkins setup building on a Mac Mini. The connection test in the system configuration also runs successfully. The behaviour is the same with the latest git snapshot or the 1.18 release

**Comment by mpfeiffermway** [comment]
I've just finished setting up a Jenkins in master/slave configuration and can confirm this issue. If the build is run on the master node the upload works as usual. Builds on a slave node cannot be uploaded (fails with the above exception).

There seems to be an issue communication information from the slave back to the master. I'll analyze the exact cause and will provide a fix once I'm done.

In the meantime, as a workaround, you can limit builds using this plugin to the master node. To do this, check the "Restrict where this project can be run" in the build configuration and enter the master node's label.

**Comment by mpfeiffermway** [comment]
Version 1.19 has been tagged and pushed, it'll typically take about 2 days for this to become available through the Jenkins store.

**Comment by mboesch** [comment]
Thank you for this superfast fix. It works like a charm.
